using System.Collections.Concurrent;
using blahaj.blahaj.Logging;
using Microsoft.Extensions.Logging;

namespace blahaj.blahaj.World.Chunks;

/// <summary>
/// Manages Chunk loading, unloading, and retrieval for a single Dimension
/// </summary>
public class ChunkManager
{
    public ChunkManager(ChunkGenerator chunkGenerator, string identifier)
    {
        Logger = LoggingProvider.NewLogger($"blahaj.blahaj.World.Chunks.ChunkManager.{identifier}");
        ChunkGenerator = chunkGenerator;
    }

    public long Seed => ChunkGenerator.Seed;
    
    private ILogger Logger { get; set; }
    
    /// <summary>
    /// Determines how a chunk will be generated by the server
    /// </summary>
    public ChunkGenerator ChunkGenerator { get; set; }
    
    public ConcurrentDictionary<ChunkPos, Chunk> LoadedChunks { get; set; } = [];

    public void Tick()
    {
        if (LoadedChunks.IsEmpty) return;
        var startTick = DateTimeOffset.Now;

        foreach (var (chunkPos, chunk) in LoadedChunks)
        {
            chunk.Tick();
        }
        
        var endTick = DateTimeOffset.Now;
        Logger.LogDebug($"Took {(endTick - startTick).TotalMilliseconds}ms to tick {LoadedChunks.Count} chunks");
    }

    public Chunk GetChunk(int x, int z) => GetChunk(new ChunkPos(x, z));

    public Chunk GetChunk(ChunkPos pos)
    {
        return LoadedChunks.TryGetValue(pos,  out var chunk) ? chunk : GenerateChunk(pos.X, pos.Z);
    }

    public bool LoadChunk(ChunkPos pos, out Chunk chunk)
    {
        if (LoadedChunks.TryGetValue(pos, out chunk))
        {
            chunk.LoaderEntities++;
            return false;
        }
        chunk = GenerateChunk(pos);
        LoadedChunks.TryAdd(pos, chunk);
        chunk.LoaderEntities++;
        return true;
    }
    
    public bool LoadChunk(int x, int z, out Chunk chunk) =>  LoadChunk(new (x, z), out chunk);

    /// <summary>
    /// Decrements the number of loading entities for a chunk, unloading the chunk if the number of entities drops to 0
    /// </summary>
    /// <param name="pos">Chunk position</param>
    /// <returns>True if the given chunk is deloaded, false is still loaded</returns>
    public bool DecrementLoaderEntities(ChunkPos pos)
    {
        if (!LoadedChunks.TryGetValue(pos, out var chunk)) return true;
        
        chunk.LoaderEntities--;
        if (chunk.LoaderEntities > 0) return false;
        LoadedChunks.TryRemove(pos, out chunk);
        return true;
    }
    
    private Chunk GenerateChunk(ChunkPos pos) => ChunkGenerator.Generate(pos);
    private Chunk GenerateChunk(int x, int z) => ChunkGenerator.Generate(x, z);
    
}