using System.Collections.Concurrent;
using blahaj.blahaj.Logging;
using Microsoft.Extensions.Logging;

namespace blahaj.blahaj.World.Chunks;

/// <summary>
/// Manages Chunk loading, unloading, and retrieval for a single Dimension
/// </summary>
public class ChunkManager
{
    public ChunkManager(ChunkGenerator chunkGenerator, string identifier)
    {
        Logger = LoggingProvider.NewLogger($"blahaj.blahaj.World.Chunks.ChunkManager.{identifier}");
        ChunkGenerator = chunkGenerator;
    }

    public long Seed => ChunkGenerator.Seed;
    
    private ILogger Logger { get; set; }
    
    /// <summary>
    /// Determines how a chunk will be generated by the server
    /// </summary>
    public ChunkGenerator ChunkGenerator { get; set; }
    
    public ConcurrentDictionary<KeyValuePair<int, int>, Chunk> LoadedChunks { get; set; } = [];

    public void Tick()
    {
        if (LoadedChunks.IsEmpty) return;
        var startTick = DateTimeOffset.Now;

        foreach (var ((chunkX, chunkZ), chunk) in LoadedChunks)
        {
            chunk.Tick();
        }
        
        var endTick = DateTimeOffset.Now;
        Logger.LogDebug($"Took {(endTick - startTick).TotalMilliseconds}ms to tick {LoadedChunks.Count} chunks");
    }

    public Chunk GetChunk(int x, int z)
    {
        return LoadedChunks.TryGetValue(new KeyValuePair<int, int>(x,z),  out var chunk) ? chunk : GenerateChunk(x, z);
    }

    public bool LoadChunk(KeyValuePair<int, int> pos, out Chunk chunk)
    {
        if (LoadedChunks.TryGetValue(pos, out chunk)) return false;
        chunk = GenerateChunk(pos);
        LoadedChunks.TryAdd(pos, chunk);
        return true;
    }
    
    public bool LoadChunk(int x, int z, out Chunk chunk) =>  LoadChunk(new KeyValuePair<int, int>(x, z), out chunk);

    private Chunk GenerateChunk(KeyValuePair<int, int> pos) => ChunkGenerator.Generate(pos);
    private Chunk GenerateChunk(int x, int z) => ChunkGenerator.Generate(x, z);
    
}